name: Publish Documentation

on:
  push:
    branches: [ main, doc-generation ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: git config --global core.autocrlf input

    - name: Setup swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: 5.8

    - run: swift --version

    - name: Setup LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15.0"

    - run: llvm-config --version

    - name: Generate LLVM pkgconfig file
      run: |
        swift package resolve &&
        .build/checkouts/Swifty-LLVM/Tools/make-pkgconfig.sh llvm.pc &&
        cat llvm.pc

    - name: Make site Directory
      run: mkdir _site

    - name: Extract Documentation
      run: |
        export PKG_CONFIG_PATH=$PWD
        swift package --allow-writing-to-directory ./_site \
          generate-documentation \
          --output-path ./_site \
          --experimental-documentation-coverage \
          --enable-inherited-docs \
          --transform-for-static-hosting \
          --hosting-base-path Val

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Fix permissions
      run: |
        chmod -v -R +rX "_site/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
